// VAPID (RFC 8292) for Web Push, hand-rolled over node:crypto — no web-push
// dependency (rule 5). VAPID is just an ES256 JWT the push service uses to
// identify the application server; the heavy lifting (an EC P-256 signature
// and base64url) is all in node:crypto. Pairs with encrypt.ts (RFC 8291
// message encryption); together they are the whole Web Push protocol.
//
// Keys: the public key is the uncompressed EC point (65 bytes, 0x04||X||Y)
// the browser passes as `applicationServerKey`; the private key is the raw
// 32-byte scalar `d`. Both are base64url in env (generated by
// scripts/make-vapid-keys.mjs).
import { createPrivateKey, generateKeyPairSync, sign } from "node:crypto";

export function b64urlEncode(buf: Buffer | Uint8Array): string {
  return Buffer.from(buf).toString("base64url");
}

export function b64urlDecode(s: string): Buffer {
  return Buffer.from(s, "base64url");
}

export type VapidConfig = {
  publicKey: string; // base64url uncompressed point
  privateKey: string; // base64url raw d
  subject: string; // mailto: or https: contact (RFC 8292)
};

// Reads the VAPID keys from env. Null (not throw) when unset, so the app runs
// before notifications are configured — same posture as the Graph/Todoist
// "not configured" paths.
export function getVapidConfig(): VapidConfig | null {
  const publicKey = process.env.VAPID_PUBLIC_KEY;
  const privateKey = process.env.VAPID_PRIVATE_KEY;
  if (!publicKey || !privateKey) return null;
  return {
    publicKey,
    privateKey,
    subject: process.env.VAPID_SUBJECT || "mailto:admin@localhost",
  };
}

// Generates a fresh VAPID keypair (used by the keygen script and verification).
export function generateVapidKeys(): { publicKey: string; privateKey: string } {
  const { publicKey, privateKey } = generateKeyPairSync("ec", {
    namedCurve: "prime256v1",
  });
  const jwkPub = publicKey.export({ format: "jwk" }) as {
    x: string;
    y: string;
  };
  const jwkPriv = privateKey.export({ format: "jwk" }) as { d: string };
  // Uncompressed point: 0x04 || X(32) || Y(32).
  const point = Buffer.concat([
    Buffer.from([0x04]),
    b64urlDecode(jwkPub.x),
    b64urlDecode(jwkPub.y),
  ]);
  return {
    publicKey: b64urlEncode(point),
    privateKey: jwkPriv.d, // already base64url 32-byte scalar
  };
}

// Rebuilds a signing KeyObject from the base64url public point + private
// scalar via a JWK (node:crypto signs from a KeyObject, not raw bytes).
function privateKeyObject(config: VapidConfig) {
  const point = b64urlDecode(config.publicKey);
  if (point.length !== 65 || point[0] !== 0x04) {
    throw new Error("VAPID_PUBLIC_KEY must be a 65-byte uncompressed EC point");
  }
  return createPrivateKey({
    format: "jwk",
    key: {
      kty: "EC",
      crv: "P-256",
      x: b64urlEncode(point.subarray(1, 33)),
      y: b64urlEncode(point.subarray(33, 65)),
      d: config.privateKey,
    },
  });
}

// Signs the VAPID JWT for one push-service origin (the `aud`). Short-lived
// (12h, under the 24h max); the push service rejects a stale or wrong-aud
// token. Returns the JWT and the public key the `Authorization: vapid` header
// pairs it with.
export function signVapidJwt(
  audience: string,
  config: VapidConfig,
  now = Date.now()
): { jwt: string; publicKey: string } {
  const header = b64urlEncode(
    Buffer.from(JSON.stringify({ typ: "JWT", alg: "ES256" }))
  );
  const payload = b64urlEncode(
    Buffer.from(
      JSON.stringify({
        aud: audience,
        exp: Math.floor(now / 1000) + 12 * 60 * 60,
        sub: config.subject,
      })
    )
  );
  const signingInput = `${header}.${payload}`;
  // ieee-p1363 gives the raw R||S (64 bytes) JWS wants, not ASN.1 DER.
  const signature = sign("sha256", Buffer.from(signingInput), {
    key: privateKeyObject(config),
    dsaEncoding: "ieee-p1363",
  });
  return {
    jwt: `${signingInput}.${b64urlEncode(signature)}`,
    publicKey: config.publicKey,
  };
}

// The push service origin is the `aud` claim (scheme://host, no path).
export function audienceFor(endpoint: string): string {
  return new URL(endpoint).origin;
}
